version: "3.9"
services:
  db:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASS}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=${DB_DB}
  web:
    image: techreads-app
    ports:
      - "80:8080"
    depends_on:
      - "db"
    command: ["./wait-for-it.sh", "db:3306", "--", "java", "-jar", "/app/techreads.war"]
    environment:
      - SPRING_PROFILES_ACTIVE=mysql
      - MYSQL_URL=jdbc:mysql://db:3306/${DB_DB}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASS=${DB_PASSWORD}